### ISSUE TITLE
KeyError when using pytorch 0.4.0

### ISSUE THREAD

**Issue by hejunqing** [WING-NUS/sequicity#11]
I am using pytorch 0.4.0 and everything is working fine except KeyError when decoding. Here is the log:
...
INFO:root:Traning time: 17.127450942993164
INFO:root:avg training loss in epoch 0 sup:5.734404
DEBUG:root:bucket 5 instance 32
DEBUG:root:bucket 7 instance 6
DEBUG:root:bucket 4 instance 41
DEBUG:root:bucket 3 instance 37
DEBUG:root:bucket 6 instance 6
DEBUG:root:bucket 2 instance 13
model.py:207: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  sup_loss += loss.data[0]
model.py:210: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  'loss:{} pr_loss:{} m_loss:{}'.format(loss.data[0], pr_loss.data[0], m_loss.data[0]))
DEBUG:root:loss:4.876643657684326 pr_loss:0.9362046718597412 m_loss:3.940438985824585
DEBUG:root:loss:4.894651889801025 pr_loss:1.3755793571472168 m_loss:3.5190725326538086
DEBUG:root:loss:5.822731971740723 pr_loss:2.3301122188568115 m_loss:3.4926199913024902
DEBUG:root:loss:5.248071193695068 pr_loss:0.7262328267097473 m_loss:4.521838188171387
DEBUG:root:loss:6.336025238037109 pr_loss:2.1582326889038086 m_loss:4.177792549133301
DEBUG:root:loss:5.730924606323242 pr_loss:1.7581840753555298 m_loss:3.972740650177002
DEBUG:root:loss:6.293116092681885 pr_loss:2.5237410068511963 m_loss:3.7693750858306885
DEBUG:root:loss:5.5927534103393555 pr_loss:2.57609224319458 m_loss:3.0166609287261963
DEBUG:root:loss:6.472774982452393 pr_loss:2.7286953926086426 m_loss:3.74407958984375
DEBUG:root:loss:5.77323579788208 pr_loss:2.192009687423706 m_loss:3.581226110458374
DEBUG:root:loss:4.7413740158081055 pr_loss:0.7590047717094421 m_loss:3.9823691844940186
DEBUG:root:loss:5.294699192047119 pr_loss:1.5785752534866333 m_loss:3.7161238193511963
DEBUG:root:loss:4.766632556915283 pr_loss:1.44969642162323 m_loss:3.3169360160827637
DEBUG:root:loss:6.531876564025879 pr_loss:2.800320863723755 m_loss:3.731555461883545
DEBUG:root:loss:4.416685104370117 pr_loss:0.7400531768798828 m_loss:3.6766321659088135
DEBUG:root:loss:5.182220458984375 pr_loss:1.5286011695861816 m_loss:3.6536190509796143
DEBUG:root:loss:5.1157097816467285 pr_loss:0.5409567952156067 m_loss:4.5747528076171875
DEBUG:root:loss:5.2725019454956055 pr_loss:1.1703280210494995 m_loss:4.102173805236816
DEBUG:root:loss:5.290111541748047 pr_loss:1.7981904745101929 m_loss:3.4919209480285645
DEBUG:root:loss:4.592691421508789 pr_loss:1.4960440397262573 m_loss:3.096647262573242
DEBUG:root:loss:5.721318244934082 pr_loss:2.510892152786255 m_loss:3.2104263305664062
DEBUG:root:loss:5.942198753356934 pr_loss:2.6059837341308594 m_loss:3.336214780807495
DEBUG:root:loss:5.035677433013916 pr_loss:0.8081327676773071 m_loss:4.227544784545898
DEBUG:root:loss:5.868890762329102 pr_loss:1.861429214477539 m_loss:4.0074615478515625
DEBUG:root:loss:5.340059280395508 pr_loss:1.6080604791641235 m_loss:3.731998920440674
DEBUG:root:loss:5.04338264465332 pr_loss:1.624698281288147 m_loss:3.418684482574463
DEBUG:root:loss:6.647482872009277 pr_loss:2.955204486846924 m_loss:3.6922783851623535
result preview...
DEBUG:root:bucket 4 instance 55
DEBUG:root:bucket 5 instance 26
DEBUG:root:bucket 2 instance 13
DEBUG:root:bucket 3 instance 30
DEBUG:root:bucket 6 instance 11
DEBUG:root:bucket 7 instance 1
Traceback (most recent call last):
  File "model.py", line 367, in <module>
    main()
  File "model.py", line 354, in main
    m.train()
  File "model.py", line 149, in train
    valid_sup_loss, valid_unsup_loss = self.validate()
  File "model.py", line 216, in validate
    self.eval()
  File "model.py", line 181, in eval
    self.reader.wrap_result(turn_batch, m_idx, z_idx, prev_z=prev_z)
  File "/hiworld/myproject/sequicity-master/reader.py", line 242, in wrap_result
    entry['generated_response'] = self.vocab.sentence_decode(gen_m[i], eos='EOS_M')
  File "/hiworld/myproject/sequicity-master/reader.py", line 112, in sentence_decode
    l = [self.decode(_) for _ in index_list]
  File "/hiworld/myproject/sequicity-master/reader.py", line 112, in <listcomp>
    l = [self.decode(_) for _ in index_list]
  File "/hiworld/myproject/sequicity-master/reader.py", line 130, in decode
    result=self._idx2item[idx]
KeyError: tensor(21)

It seems that _ in line 112 sometimes is of type int, sometime is tensor? What is wrong?

**Comment by hejunqing** [comment]
I change replace line 181 in eval with the following lines and it works fine:
m_idx_=[[_.item() for _ in sent] for sent in m_idx ]
z_idx_=[[_.item() for _ in sent] for sent in z_idx ]
self.reader.wrap_result(turn_batch, m_idx_, z_idx_, prev_z=prev_z)
