### ISSUE TITLE
KeyError: 'generated_latent'

### ISSUE THREAD

**Issue by linxiaoby** [WING-NUS/sequicity#2]
Something was wrong  in function run_metrics() when I tried to  train,  it seems that the dict _turn_ has no key 'generated_latent'.  

+++++++++++++++++++++
Traceback (most recent call last):
  File "model.py", line 368, in <module>
    main()
  File "model.py", line 355, in main
    m.train()
  File "model.py", line 151, in train
    valid_sup_loss, valid_unsup_loss = self.validate()
  File "model.py", line 217, in validate
    self.eval()
  File "model.py", line 186, in eval
    res = ev.run_metrics()
  File "D:\AllCode\PyCode\NLP\Dialogue\sequicity\metric.py", line 219, in run_metrics
    match = self.match_metric(data, 'match', raw_data=raw_data)
  File "D:\AllCode\PyCode\NLP\Dialogue\sequicity\metric.py", line 111, in wrapper
    res = func(*args, **kwargs)
  File "D:\AllCode\PyCode\NLP\Dialogue\sequicity\metric.py", line 264, in match_metric
    gen_latent = turn['generated_latent']
KeyError: 'generated_latent'

+++++++++++++++++++++
I have printed the _turn_, it looks like this:

 OrderedDict([('dial_id', '545'), ('turn_num', '0'), ('user', 'i am looking for a restaurant in the west part of town .'), ('generated_bspan',
'west west EOS_Z1'), ('bspan', 'west EOS_Z1'), ('generated_response', '<GO> name_SLOT is . </s>'), ('response', '<GO> there are 14 restaurants
 in the area_SLOT . are you looking for a particular cuisine ? </s>'), ('u_len', '14'), ('m_len', '17'), ('supervised', 'True')])
+++++++++++++++++++++
Thanks for your help!

**Comment by lwqlwq** [comment]
Fixed. Thanks
