### ISSUE TITLE
something wrong while testing kvret ,how to solve it

### ISSUE THREAD

**Issue by terryqj0107** [WING-NUS/sequicity#9]
Traceback (most recent call last):
  File "model.py", line 366, in <module>
    main()
  File "model.py", line 359, in main
    m.eval()
  File "model.py", line 184, in eval
    res = ev.run_metrics()
  File "/data/jquan/codes/sequicity-master/metric.py", line 332, in run_metrics
    match_rate = self.match_rate_metric(data, 'match')
  File "/data/jquan/codes/sequicity-master/metric.py", line 111, in wrapper
    res = func(*args, **kwargs)
  File "/data/jquan/codes/sequicity-master/metric.py", line 419, in match_rate_metric
    bspan_data = pickle.load(open(bspans,'rb'))
FileNotFoundError: [Errno 2] No such file or directory: './data/kvret/test.bspan.pkl'

**Comment by linxiaoby** [comment]
I have the same error, do you find a solution?

**Comment by shizhediao** [comment]
Hi, sorry to reply late.
I've fixed this problem and you can see here #7
Also you can view my forked repo https://github.com/shizhediao/sequicity
